# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements_dev.txt
  - pip install pytest pytest-cov coveralls

# command to run tests, e.g. python setup.py test
script:
  - python -m pytest --cov tests/
  - coveralls

# deploy new versions to PyPI
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: hover2pi
  password:
    secure: B0b0th#dog123pypi
  on:
    tags: true
    repo: hover2pi/specialsoss
    python: 3.5